# Generated by Django 3.2.5 on 2021-08-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dojos_ninjas'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojos',
            name='desc',
            field=models.CharField(default='Old Dojo', max_length=45),
        ),
    ]
